#!/usr/bin/env python3

try:
    from bs4 import BeautifulSoup
    import requests
except ImportError:
    import sys
    print('please run `pip3 install requests beautifulsoup4 ndg-httpsclient`')
    sys.exit(1)


def get_tweet_id():
    resp = requests.get('https://twitter.com/antibullyranger')
    soup = BeautifulSoup(resp.content, 'html.parser')
    for tweet_div in soup.select('.tweet'):
        if 'user-pinned' in tweet_div['class']:
            continue
        return tweet_div['data-tweet-id']


def get_tweet_url():
    return (
        'https://twitter.com/antibullyranger/status/{}'
        .format(get_tweet_id())
    )


if __name__ == '__main__':
    print(get_tweet_url())
